# Remove version as it's now optional and causing warnings
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: user-system-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - user-system-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: user-system-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/user-system
    depends_on:
      - mongodb
    networks:
      - user-system-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - user-system-network
    restart: unless-stopped

networks:
  user-system-network:
    driver: bridge

volumes:
  mongodb_data: